GET http://localhost:4000/twits?page=2&perPage=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMGZhZjVhNWMtYzI3Mi00ZTAzLWExMWMtY2I0MjY0ZDllMTQ3IiwibmFtZSI6Ik9iYWZlbWkiLCJ1c2VybmFtZSI6ImhvYmFyIiwiZW1haWwiOiJ0aGV2ZXRkb2N0b3JAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImltYWdlVXJsIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vdGhldmV0ZG9jdG9yL2ltYWdlL3VwbG9hZC92MTY0MzYxNzg5My9jb3phLzE2MTMxNDM4MTY1ODVfZ3NvNHFrLmpwZyIsImJpbyI6IkkgYW0gcGFzc2lvbmF0ZSBhYm91dCB0dXJuaW5nIGlkZWFzIGludG8gcmVhbC1saWZlIHN1c3RhaW5hYmxlIHByb2plY3RzLiIsImxvY2F0aW9uIjoiTmFpamEsIE5pZ2VyaWEiLCJkb2IiOm51bGwsIm1vYmlsZSI6IisyMzQ4MDY5MTAwNDgzIiwidmVyaWZpZWQiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjEtMTEtMzBUMDc6MjA6NDEuODczWiIsInVwZGF0ZWRBdCI6IjIwMjItMDItMDdUMTI6MjA6MzMuNTk0WiJ9LCJpYXQiOjE2NDQ1MjMwNDJ9.lpdHqLUvFPukEoYSryUkZnivEzt-7i9KjN5vFxP9cI4