# GET http://localhost:4000/twits?page=70&perPage=1
# Content-Type: application/json
# Authorization: Bearer 'token'

PATCH http://localhost:4000/auth/5d5380d0-26b2-4a76-b719-3e2a97777306
Content-Type: application/json
Authorization: Bearer 